version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: tm-anomaly-tracker-postgres
    environment:
      POSTGRES_USER: tm-anomaly-tracker-db-user
      POSTGRES_PASSWORD: tm-anomaly-tracker-db-pass
      POSTGRES_DB: tm-anomaly-tracker-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: tm-anomaly-tracker-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tm-anomaly-tracker-db
      SPRING_DATASOURCE_USERNAME: tm-anomaly-tracker-db-user
      SPRING_DATASOURCE_PASSWORD: tm-anomaly-tracker-db-pass
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data:
